### ISSUE TITLE
allow verbs

### ISSUE THREAD

**Issue by Wes4329** [Pandora-Intelligence/concise-concepts#11]
Looks like patterns currently prevent verbs?
                    individual_pattern = {
                        "lemma": {"regex": r"(?i)" + word},
                        "POS": {"NOT_IN": ["VERB"]},
                        "DEP": {"NOT_IN": ["nsubjpass"]},
                    }

**Comment by davidberenstein1957** [comment]
Thank you for the feedback. I'm taking a look now.

**Comment by davidberenstein1957** [comment]
@Wes4329 this can now be done via a variable during initialization `exclude_pos`, which determines what POS ought to be excluded from the matching.
