### ISSUE TITLE
Python latest package 0.6.2 failing. Error in Conceptualizer.py

### ISSUE THREAD

**Issue by prakhar251998** [Pandora-Intelligence/concise-concepts#15]
Hi @davidberenstein1957 ,the latest update version 0.6.2 is not working via pip. It is still installing 0.6.1 
I tried manually making the changes as per the latest in the conceptualizer.py file.
Even there on testing it gives the following error.
~\anaconda3\lib\site-packages\concise_concepts\conceptualizer\Conceptualizer.py in run(self)
     97             self.resolve_overlapping_concepts()
     98         self.infer_original_data()
---> 99         self.create_conceptual_patterns()
    100 
    101         if not self.ent_score:

~\anaconda3\lib\site-packages\concise_concepts\conceptualizer\Conceptualizer.py in create_conceptual_patterns(self)
    359                                     }
    360                                 )
--> 361 
    362         add_patterns(self.data)
    363         add_patterns(self.original_data)

~\anaconda3\lib\site-packages\concise_concepts\conceptualizer\Conceptualizer.py in add_patterns(input_dict)
    327                             if self.case_sensitive:
    328                                 specific_copy[self.match_key] = "{op}".join(word_parts)
--> 329                             else:
    330                                 specific_copy[self.match_key] = {
    331                                     "regex": r"(?i)"

NameError: name 'specific_copy' is not defined.

My estimate is it is because of the following lines. I tried solving on my end but wasn't successful.
All the previous problems regarding custom custom word2vec stands as-it-is.
Kindly look into this ASAP
<img width="954" alt="error" src="https://user-images.githubusercontent.com/42132495/192454535-f1dc4aa0-9b7a-4912-a66f-7b91c5176678.png">

**Comment by davidberenstein1957** [comment]
I resolved this with a change, however, the 0.6.2 version needs additional testing before being released officially.

**Comment by prakhar251998** [comment]
data = {
    "fruit": ["apple", "pear", "orange"],
    "vegetable": ["broccoli", "spinach", "tomato"],
    "meat": ["beef", "pork", "fish", "lamb"]
}

text = """
    Heat the oil in a large pan and add the Onion, celery and carrots.
    Then, cook over a medium–low heat for 10 minutes, or until softened.
    Add the courgette, garlic, red peppers and oregano and cook for 2–3 minutes.
    Later, add some oranges and chickens. """
model_path = "glove-twitter-25"
nlp = spacy.load("en_core_web_lg",disable=['ner'])
nlp.add_pipe("concise_concepts", config={"data": data,"model_path": model_path,"ent_score":True})
doc = nlp(text)


On this orginal example input,we get the following output,very bad classification.Worse than previous versions
<img width="604" alt="image" src="https://user-images.githubusercontent.com/42132495/192497421-f5d2d043-7954-4121-87c7-e8c7855bf236.png">
It seems the result has deteriorated .Kindly see to this

**Comment by prakhar251998** [comment]
Also getting the following error when checking for the following data

data = {
    "performance":  ['mileage','speed','fuel','capacity','transmisson'],
    "engine":       ['turbo','cylinder','gear','engine'],
    'brakes':       ['disc','suspension','brakes'],
    "dimensions":   ['length','width','height','seating','doors'],
    "comfort":      ['steering','heater','air', 'accessory','headrest','charger','luxury'],
    "entertainment":['radio','speaker','phone','touch'],
    'safety':       ['alarm','theft','warning','safety']
}

text ="""
XUV 700 is first in class luxury SUV brought to you by Mahindra.
The 13-inch instrument cluster and attached infotainment panel 
are just the best in class and add a classy look to the SUV.
The XUV 700 is a beast of a car with that panoramic sunroof,
and leather upholstery on the seats and doesn't compromise on the luxury of the passengers. 
The adaptive cruise control is a top-end feature clearly not offered in any
other cars of this segment at this price point. Have always been a fan of the XUV 500
but the successor is a beast with the luxury of its own kind the road experience is pretty smooth
and the engine performs really well.
"""
model_path = "glove-twitter-25"
nlp = spacy.load("en_core_web_lg",disable=['ner'])
nlp.add_pipe("concise_concepts", config={"data": data,"model_path": model_path,"ent_score":True})
doc = nlp(text)

<img width="667" alt="image" src="https://user-images.githubusercontent.com/42132495/192498462-47e8eb09-f182-4919-ab22-7c1852a09155.png">
Why is it taking the argument as none type

**Comment by prakhar251998** [comment]
Hi @davidberenstein1957 ,what does the following warning implies
<img width="578" alt="image" src="https://user-images.githubusercontent.com/42132495/192499462-fdcd6c53-86ac-4ca0-92c5-8ee25867eab7.png">

**Comment by davidberenstein1957** [comment]
> data = { "fruit": ["apple", "pear", "orange"], "vegetable": ["broccoli", "spinach", "tomato"], "meat": ["beef", "pork", "fish", "lamb"] }
> 
> text = """ Heat the oil in a large pan and add the Onion, celery and carrots. Then, cook over a medium–low heat for 10 minutes, or until softened. Add the courgette, garlic, red peppers and oregano and cook for 2–3 minutes. Later, add some oranges and chickens. """ model_path = "glove-twitter-25" nlp = spacy.load("en_core_web_lg",disable=['ner']) nlp.add_pipe("concise_concepts", config={"data": data,"model_path": model_path,"ent_score":True}) doc = nlp(text)
> 
> On this orginal example input,we get the following output,very bad classification.Worse than previous versions <img alt="image" width="604" src="https://user-images.githubusercontent.com/42132495/192497421-f5d2d043-7954-4121-87c7-e8c7855bf236.png"> It seems the result has deteriorated .Kindly see to this

the quality deterioration is caused by the glove model, which is lousy. Similarly, you should pass `exclude_pos` and `exclude_dep` parameters to filter out POS and dependencies like for example verbs.

**Comment by prakhar251998** [comment]
I can understand this logic for different glove models But this glove-twitter-25 model was the default model used by Concise concepts earlier version.How did it deterioate so bad.
Can you please post a couple of examples highlighting use of new parameters exclude_pos  & exclude_dep
,

**Comment by prakhar251998** [comment]
Hi @davidberenstein1957 ,any update regarding the Nonetype Error and the entity [] not found in model warning that we are getting?

**Comment by davidberenstein1957** [comment]
I resolved this with a more recent commit. Also, the config for exclude_pos and exclude_dep has been updated to a more general default. Lastly, I changed the model in the default copy-paste example to a more robust word2vec model.
