### ISSUE TITLE
Unable to load local custom gensim model

### ISSUE THREAD

**Issue by Hevia** [Pandora-Intelligence/concise-concepts#16]
I am trying to use concise-concepts with a custom word2vec model I trained using gensim. Here is a link to my notebook: https://github.com/EarthNLP/ClimateScholar/blob/users/hevia/concise-concepts-ner/research/Concise_Concepts.ipynb

The error & code in question:
![image](https://user-images.githubusercontent.com/15069763/194118881-f84ac01e-f828-4d92-ae1b-1353f20fac71.png)

Looking at the code: https://github.com/Pandora-Intelligence/concise-concepts/blob/main/concise_concepts/conceptualizer/Conceptualizer.py#L147

I tried to load my model the same way it is written here, and it works just fine:
![image](https://user-images.githubusercontent.com/15069763/194123385-f852a50a-1f9d-42a5-925a-2859ee033b5d.png)

The documentation doesnt mention any specific restrictions with loading models (unless you cant load local models?): https://github.com/Pandora-Intelligence/concise-concepts#use-gensimword2vec-model-from-pre-trained-gensim-or-custom-model-path, but I did notice that the example used a blank spaCy: https://github.com/Pandora-Intelligence/concise-concepts/blob/main/concise_concepts/examples/example_gensim_custom.py which I tried and also did not work.

I am also running gensim 4.X+

Hopefully its a minor issue on my end, just so it means you don't have to do any work 😅, the library is awesome and would love to try it out with some of our custom word embeddings

Thanks for your time!

**Comment by davidberenstein1957** [comment]
@Hevia I think you are using an old version of 'concise-concepts'. Could you try installing the latest version? Also, excellent that you are working on NLP for climate. Please let me know if I can join in and help with anything or contribute. I do some volunteering for https://www.510.global/, where they also have interesting NLP topics from time to time.

**Comment by Hevia** [comment]
@davidberenstein1957 Yep switching to latest version fixed it! Thank you :)

Thanks for your offer to help. This started off as a hackathon project, but once we get the core concept in a more stable place, we'll be looking for contributors! I'll reach back out then!
