### ISSUE TITLE
matching_patterns.json

### ISSUE THREAD

**Issue by koaning** [Pandora-Intelligence/concise-concepts#18]
Is it possible to change the `"matching_patterns.json"` name? These pattern files can be instrumental in combination with Prodigy, but I might want to generate a few upfronts. 

It might also be a good idea to document this file more explicitly in the README, I only found out about it by accident when I was looking at the folder that was running my code.

**Comment by davidberenstein1957** [comment]
@koaning Thanks for the feedback, I will probably find some time this weekend to improve on this.

**Comment by koaning** [comment]
Sure thing!

By the way, I'm working on a tutorial that involves this tool. Are there any features you feel are underappreciated that might deserve some extra attention?
