### ISSUE TITLE
Code example did not work

### ISSUE THREAD

**Issue by philipvollet** [Pandora-Intelligence/concise-concepts#2]
I tried to give your library a test run and installed it via>> 'pip install classy-classification' and git, but the code example did not work. I haven't taken the time to troubleshoot. I guess something has been renamed 'concise_concepts' vs 'classy_classification' ?

**Comment by davidberenstein1957** [comment]
> I tried to give your library a test run and installed it via>> 'pip install classy-classification' and git, but the code example did not work. I haven't taken the time to troubleshoot. I guess something has been renamed 'concise_concepts' vs 'classy_classification' ?

Concise concepts (few shot ner) and classy classification (few/zero short classification) are two separate packages. There was a typo in the readme, mentioning the install of the wrong package. I resolved this now.

**Comment by davidberenstein1957** [comment]
@philipvollet By the way, classy-classification has already been added to the [spaCy universe](https://spacy.io/universe/project/classyclassification), while I have a [PR ](https://github.com/explosion/spaCy/pull/10499)for concise-concepts.
