### ISSUE TITLE
Custom models showing different confidences even 0 in case of mixed casing text

### ISSUE THREAD

**Issue by prakhar251998** [Pandora-Intelligence/concise-concepts#25]
<img width="581" alt="image" src="https://user-images.githubusercontent.com/42132495/204722819-b534f1ec-81ef-4084-a61f-5ba826cc76c6.png">
Code used is given below. Even my own trained custom model showing the same behaviour

import spacy
from spacy import displacy

import concise_concepts

model_path ="glove-wiki-gigaword-300"

os.environ['KMP_DUPLICATE_LIB_OK']='True'
data = {
    "fruit": ["apple", "pear", "orange"],
    "vegetable": ["broccoli", "spinach", "tomato"],
    "meat": ["beef", "pork", "fish", "lamb"],
}

text = """
    Heat the oil in a large pan and add the ONION, Celery and carrots.
    onion is must.CELERY is optional
    Then, cook over a medium–low heat for 10 minutes, or until softened.
    Add the courgette, garlic, red peppers and oregano and cook for 2–3 minutes.
    Garlic paste can also be used instead of Raw GARLIC 
    Later, add some oranges and chickens.
    Vegetarain may add cottage cheese instead of CHICKENS"""

nlp = spacy.load("en_core_web_lg", disable=["ner"])

nlp.add_pipe(
    "concise_concepts",
    config={
        "data": data,
        "model_path":model_path,
        "ent_score": True,  # Entity Scoring section
        "verbose": True,
        "exclude_pos": ["VERB", "AUX"],
        "exclude_dep": ["DOBJ", "PCOMP"],
        "include_compound_words": False,
        "json_path": "./fruitful_patterns.json",
    },
)
doc = nlp(text)

options = {
    "colors": {"fruit": "darkorange", "vegetable": "limegreen", "meat": "salmon"},
    "ents": ["fruit", "vegetable", "meat"],
}

ents = doc.ents
for ent in ents:
    new_label = f"{ent.label_} ({ent._.ent_score:.0%})"
    options["colors"][new_label] = options["colors"].get(ent.label_.lower(), None)
    options["ents"].append(new_label)
    ent.label_ = new_label
doc.ents = ents

**Comment by davidberenstein1957** [comment]
Hello, Thank for noticing this. Confidences are based on the embeddings in the word2vec but I think this check currently doesn't include capitalization even if they are recognized. I will take a closer look next week.

**Comment by davidberenstein1957** [comment]
@prakhar251998 thanks for your input💪🏽 I found several small bugs, so this really improved entity scoring performance!
