### ISSUE TITLE
Loading a local NER model but has no embeddings

### ISSUE THREAD

**Issue by marcossilva** [Pandora-Intelligence/concise-concepts#3]
Hi! I have a local trained model which only has NER in its pipeline and as soon as I try to add the concise-concepts data it returns
```
Exception: Choose a model with internal embeddings i.e. md or lg.
```

How can I train my model to have the necessary embeddings to work out with concise-concepts?

**Comment by davidberenstein1957** [comment]
I could be that you don't have embeddings within the spaCy model. Try out `concise-concepts==0.3.0` for using custom Gensim embeddings.

**Comment by davidberenstein1957** [comment]
https://github.com/Pandora-Intelligence/concise-concepts#use-gensimword2vec-model-from-pre-trained-gensim-or-custom-model-path

**Comment by davidberenstein1957** [comment]
@marcossilva I recommend looking at the spaCy guide on [embeddings](https://spacy.io/usage/embeddings-transformers) or [training ](https://spacy.io/usage/training). Alternatively, there is Gensim, you could also try to use a [FastText ](https://radimrehurek.com/gensim/models/fasttext.html) model from Gensim to deal with OOV words for your specific dataset, or even better, just [train a custom word2vec model](https://radimrehurek.com/gensim/auto_examples/tutorials/run_word2vec.html#training-your-own-model) for your data.
