### ISSUE TITLE
Model Sensitivity

### ISSUE THREAD

**Issue by nv78** [Pandora-Intelligence/concise-concepts#31]
Noticed that the concise concepts model isn't too sensitive. For instance, in the text block in the tutorial:

text = """
    Heat the oil in a large pan and add the Onion, celery and carrots.
    Then, cook over a medium–low heat for 10 minutes, or until softened.
    Add the courgette, garlic, red peppers and oregano and cook for 2–3 minutes.
    Later, add some oranges and chickens. """
    
We are only picking up 1 or 2 of the fruits and vegetables, not all of them. Is there any way to adjust this?

**Comment by davidberenstein1957** [comment]
Hi, this can be adjusted by using the `topn` parameter or by using another embedding model. I recommend training a custom one.
