### ISSUE TITLE
Avoid pipeline crashing if a word is not found in the embeddings table

### ISSUE THREAD

**Issue by dvsrepo** [Pandora-Intelligence/concise-concepts#7]
Hi @davidberenstein1957 !

I'm testing this with Italian medical concepts and as some are pretty specific I ran into the following issue:

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/concise_concepts/conceptualizer/__init__.py in expand_concepts(self)
     90             remaining_values = [self.data[rem_key] for rem_key in remaining_keys]
     91             remaining_values = list(itertools.chain.from_iterable(remaining_values))
---> 92             similar = self.kv.most_similar(
     93                 positive=self.data[key] + [key],
     94   
KeyError: "Key 'Ultrasuonoterapia' not present"

After running:

```python
data = {
    "PRESTAZIONE": list(df.PRESTAZIONE.unique()) # this is a list of Italian terms
}
nlp = spacy.load("it_core_news_lg", disable=["ner"])
nlp.add_pipe("concise_concepts", config={"data": data, "ent_score": True})
```
I'd likely need to clean my list before setting the cc pipeline, but what I would expect is:

- A warning telling me my term was not found in the embeddings, and maybe still letting me build the pipeline. Maybe this could be set with a param like skip not found terms.
- Or a a more descriptive error, telling me to remove the term in question from my list.

**Comment by pelayoarbues** [comment]
Same issue with a Spanish pipeline using "es_core_news_lg"

**Comment by davidberenstein1957** [comment]
@pelayoarbues Sloppy of me, it is resolved in 0.5.2 now.

**Comment by davidberenstein1957** [comment]
@pelayoarbues The most recent version 0.5.3 works. The data being used in my tests was a bit lacking so I didn't pick up on all potential mistakes. It works now.

**Comment by pelayoarbues** [comment]
Solved! Thank you very much!
