### ISSUE TITLE
Key not present in word2vec model

### ISSUE THREAD

**Issue by VSK02101996** [Pandora-Intelligence/concise-concepts#9]
key fruit not present in word2vec model
key vegetable not present in word2vec model
key meat not present in word2vec model

This is the error I am getting , when I tried to run the example  ?

**Comment by davidberenstein1957** [comment]
@VSK02101996 
This would suggest that the words are not present in the vectors dictionary you are currently using. I would suggest training a custom model or using one of the default, more elaborate, models provided by gensim. See the model section in the Readme.

**Comment by davidberenstein1957** [comment]
Could you send me some reproducible code please?

**Comment by VSK02101996** [comment]
`import spacy
from spacy import displacy

import concise_concepts

data = {
    "fruit": ["apple", "pear", "orange"],
    "vegetable": ["broccoli", "spinach", "tomato", "garlic", "onion", "beans"],
    "meat": ["beef", "pork", "fish", "lamb", "bacon", "ham", "meatball"],
    "dairy": ["milk", "butter", "eggs", "cheese", "cheddar", "yoghurt", "egg"],
    "herbs": ["rosemary", "salt", "sage", "basil", "cilantro"],
    "carbs": ["bread", "rice", "toast", "tortilla", "noodles", "bagel", "croissant"],
}

text = """
    Heat the oil in a large pan and add the Onion, celery and carrots. 
    Then, cook over a medium–low heat for 10 minutes, or until softened. 
    Add the courgette, garlic, red peppers and oregano and cook for 2–3 minutes.
    Later, add some oranges and chickens. """

model_path = "/content/word2vec.wordvectors"

nlp = spacy.load("en_core_web_md", disable=["ner"])
nlp.add_pipe("concise_concepts", config={"data": data,"model_path":model_path,"ent_score": True,})
doc = nlp(text)

options = {
    "colors": {
        "fruit": "darkorange",
        "vegetable": "limegreen",
        "meat": "salmon",
        "dairy": "lightblue",
        "herbs": "darkgreen",
        "carbs": "lightbrown",
    },
    "ents": ["fruit", "vegetable", "meat", "dairy", "herbs", "carbs"],
}

ents = doc.ents
for ent in ents:
    new_label = f"{ent.label_} ({float(ent._.ent_score):.0%})"
    options["colors"][new_label] = options["colors"].get(ent.label_.lower(), None)
    options["ents"].append(new_label)
    ent.label_ = new_label
doc.ents = ents

displacy.render(doc, style="ent", options=options)`

This is the code I am using

**Comment by VSK02101996** [comment]
from gensim.models import Word2Vec
dataset = api.load("text8")
model = Word2Vec(dataset)

Now the error is , cannot compute mean with no input .

**Comment by VSK02101996** [comment]
For word2vec.model  file I got error argument of type 'Word2Vec' is not iterable"

**Comment by VSK02101996** [comment]
I am trying this in colab , it is giving me error argument of type 'Word2Vec' is not iterable again

**Comment by VSK02101996** [comment]
https://colab.research.google.com/drive/1G6VurQf4piogj7zylWB2VuHlrtOU0mtu?usp=sharing 

Link for colab

**Comment by VSK02101996** [comment]
Please if possible can you resolve this issue

**Comment by davidberenstein1957** [comment]
@VSK02101996 can you send me the entire error stacktrace and a link to the "word2vec.wordvectors" file that you are using.

**Comment by davidberenstein1957** [comment]
Also, please check whether you versioning aligns with the most recent version of concise-concepts and its requirements.

**Comment by VSK02101996** [comment]
Thanks it works now.
